### ISSUE TITLE
Can't open it.

### ISSUE THREAD

**Issue by HippotamusAmphibious** [YTP-Plus/YTPPlusPlusPlus#1]
Hello, I didn't know there's a new version of the YTP generator that was launched so recently, glad to be the first one for using your version!

but there's one problem, everytime I try to open it, nothing appears and the startup sound abruptly cuts for 5 seconds..

I used the requirements you included in your site, *and to be honest it was easy because these are the same requirements from YTP+ CLI, expect there are new ones on this version, thanks for some youtube tutorial* but I have no idea if i'm still missing something to make it to work.

**Comment by ccateni** [comment]
Did you follow the instructions and install the software required?
https://ytp-plus.github.io/#/README.md

**Comment by KiwifruitDev** [comment]
Try [v3.0.1](https://github.com/YTP-Plus/YTPPlusPlusPlus/releases) to see if this solves the issue.

**Comment by HippotamusAmphibious** [comment]
apparently it was the python plugin that is not making the program open up I just figured out right now, thanks for updating the release though.
