### ISSUE TITLE
Bug in setup

### ISSUE THREAD

**Issue by LovelyProductions** [YTP-Plus/YTPPlusPlusPlus#10]
**Suggested Prerequisites**
- [ ] I have read the [installation instructions](https://github.com/YTP-Plus/YTPPlusPlusPlus/blob/main/README.md) before proceeding.
- [ ] I have searched the [#guide](https://discord.com/channels/641428540486844417/1092579601156415498) forum posts on the [YTP+ Hub Discord](https://discord.gg/8ppmspR6Wh) for a solution to my problem before proceeding.
- [ ] I have searched [GitHub issues](https://github.com/YTP-Plus/YTPPlusPlusPlus/issues) to see if this issue has already been reported before proceeding.

**Describe the bug**
Error loading plugins: An error occurred trying to start process 'python' with working directory 'C:\Users\madis\Downloads\ytpplusplusplus309\plugins'. The system cannot find the file specified.

**To Reproduce**

**Expected behavior**
It was supposed to install, but instead gave an error.

**Screenshots**

**Desktop:**
 - OS: Windows 11
 - Version: IDK

**Additional context**

**Comment by KiwifruitDev** [comment]
Try using the latest release (v3.0.10 as of writing) since it now treats Python as an optional dependency.

**Comment by KiwifruitDev** [comment]
There isn't enough information to keep this issue open, so I'll close it for you. Let me know if you encounter any further problems and I'll re-open it.
