### ISSUE TITLE
Input string was not in a correct format.

### ISSUE THREAD

**Issue by gregzoz** [YTP-Plus/YTPPlusPlusPlus#11]
**Describe the bug**
Inability to render video 

**To Reproduce**
1. Go to 'YTP++ Generate tab'
2. Click on 'Render'
3. See error "Input string was not in a correct format."

**Console**
Searching for plugins in .\plugins...
Loading bat plugins...
Loading js plugins...
Loading py plugins...
Loaded plugin dance.py.
Initialization complete.
Generation started.
Seed: 511
Temporary directory deleted.
.\library\video\materials\test.mp4
CLIP DURATION: 50,05
STARTING CLIP video0
An error occurred while generating the video.
Input string was not in a correct format.

**Desktop:**
 - OS: Windows 10 LTSC
 
I have tried removing the spaces in the names of materials. I have tried removing all of the materials and leaving only the necessary ones to make it work, but it's the same error no matter what.

**Comment by KiwifruitDev** [comment]
Is YTP+++ installed in a directory without spaces and was the deploy script used? Also, this may be a problem related to FFmpeg/FFprobe or Windows localization (such as languages). Please let me know.

**Comment by Kobun42** [comment]
Don't know if I should interject but from my testing it seems to be plugins and ffmpeg causing it... at least after updating from the prior version of YTP+++. It used to work fine prior to the update but distort.ps1 and a couple others love to throw that error a lot and it's getting on my nerves. I even reinstalled the program using the deploy script and absolutely nothing changed.

No spaces in my directories or sources too, not sure wtf is going on with it, and console doesn't reveal much other than it's a plugin+ffmpeg thing.

**Comment by KiwifruitDev** [comment]
> Don't know if I should interject but from my testing it seems to be plugins and ffmpeg causing it... at least after updating from the prior version of YTP+++. It used to work fine prior to the update but the distort.ps1 plugin and a couple others (pitch.ps1 as well, actually most plugins if I'm being honest. just those two cause it the most from my testing) love to throw that error a lot and it's getting on my nerves. I even reinstalled the program using the deploy script and absolutely nothing changed.
> 
> No spaces in my directories or sources too, not sure wtf is going on with it, and console doesn't reveal much other than it's a plugin+ffmpeg thing.

See #14.

**Comment by Kobun42** [comment]
> > Don't know if I should interject but from my testing it seems to be plugins and ffmpeg causing it... at least after updating from the prior version of YTP+++. It used to work fine prior to the update but the distort.ps1 plugin and a couple others (pitch.ps1 as well, actually most plugins if I'm being honest. just those two cause it the most from my testing) love to throw that error a lot and it's getting on my nerves. I even reinstalled the program using the deploy script and absolutely nothing changed.
> > No spaces in my directories or sources too, not sure wtf is going on with it, and console doesn't reveal much other than it's a plugin+ffmpeg thing.
> 
> See #14.

That seemed to do it for the most part. Although distort.ps1 is still broken, had to disable that one manually but afterwards everything else works.

**Comment by KiwifruitDev** [comment]
This software is no longer supported.

https://store.steampowered.com/app/2516360/Nonsensical_Video_Generator/
