### ISSUE TITLE
Fatal Error while getting length of video

### ISSUE THREAD

**Issue by MartindaYosh** [YTP-Plus/YTPPlusPlusPlus#13]
I discovered a strange bug where I tried to render a video but I got an error that said: "Fatal Error while getting length of video" What does that mean?

**Comment by KiwifruitDev** [comment]
Try updating to v3.1.0 (replacing old v4 ImageMagick binaries as per #14) and report back if that solves it. :)

**Comment by MartindaYosh** [comment]
Hello there, I tried updating YTPPlusPlusPlus but the error is still present… Any other way to fix this? Neobsahuje žádné viry.www.avg.com

**Comment by KiwifruitDev** [comment]
I made an effort to include FFmpeg from now on, try using v3.1.3 now.

**Comment by KiwifruitDev** [comment]
This software is no longer supported.

https://store.steampowered.com/app/2516360/Nonsensical_Video_Generator/
