### ISSUE TITLE
v3.1.7: Image preset produces corrupted videos

### ISSUE THREAD

**Issue by Kobun42** [YTP-Plus/YTPPlusPlusPlus#15]
**Describe the bug**
When making a video in YTP+++ v3.1.7, the video output is corrupted and depending on the amount of clips may either have some minor issues or may not be able to be read by either Windows Media Player or VLC Media Player.

**To Reproduce**
1. Generate a new video
2. Wait for it to output
3. Video file should be created but it has issues depending on amount of clips used (low amount of clips like 2-5 videos causes discrepancy with video length but is viewable, a large amount 350 videos doesn't work at all)

**Expected behavior**
Video should be playable in either media player without issues.

**Desktop:**
 - OS: Windows 10
 - Version 22H2

**Additional context**
Videos created weren't corrupted on v3.1.5 prior to updating to v3.1.7, not sure what the cause is. All videos made with prior versions of YTP+++ are still viewable without much issues in either media player.

**Comment by KiwifruitDev** [comment]
Which input settings are you using? Are images enabled?
Please send a copy of `console.txt` and `Options.json`.

**Comment by Kobun42** [comment]
[Options.json can be found at this pastebin link because github doesn't let me upload it yay.](https://pastebin.com/4y5L5eq6)

Gonna hold off on console.txt right now as I have no clue if this has been fixed by restarting or if 100 clips is a sweet spot. Gonna need to do more testing real quick.

**Comment by Kobun42** [comment]
Did notice in my last console.txt output a TON of this message, but it seems 150 clips worked fine regardless and the program seems to be flip-flopping between working and not working fine so I have no clue what's going on right now:
`[mp4 @ 000001e8b6d7e900] Non-monotonous DTS in output stream 0:1; previous: 7622884, current: 7244702; changing to 7622885. This may result in incorrect timestamps in the output file.`

**Comment by KiwifruitDev** [comment]
It might be due to the image functionality, it's a bit broken atm so I'll keep this issue up for that.
Try rendering with 0% image chance to see if that helps.

**Comment by Kobun42** [comment]
Okay, I'll see about that. I only had 2 images anyways so no big loss there for now.

**Comment by Kobun42** [comment]
It seems to work for the most part but I've noticed a consistent trend of "Trying a different method of concatenation" which ALSO produces corrupted videos...

**Comment by KiwifruitDev** [comment]
This software is no longer supported.

https://store.steampowered.com/app/2516360/Nonsensical_Video_Generator/
