### ISSUE TITLE
Input string was not in a correct format.

### ISSUE THREAD

**Issue by kiroffYT** [YTP-Plus/YTPPlusPlusPlus#16]
Console.txt

Initialization complete for v3.1.7.
User acknowledged photosensitive warning.
No updates available.
Checking for dependencies...
magick found.
Searching for plugins in .\plugins...
Loading bat plugins...
Loading ps1 plugins...
Added video library BOOM from plugin boom.ps1.
Plugin boom.ps1 added 1 libraries.
Loaded plugin boom.ps1.
Plugin dance.ps1 added 2 settings.
Loaded plugin dance.ps1.
Added audio library Distort from plugin distort.ps1.
Plugin distort.ps1 added 1 libraries.
Loaded plugin distort.ps1.
Plugin dsp.ps1 added 4 settings.
Loaded plugin dsp.ps1.
Loaded plugin mirrorsymmetry.ps1.
Loaded plugin pitch.ps1.
Loaded plugin randomsound.ps1.
Added audio library Rave_Music from plugin rave.ps1.
Plugin rave.ps1 added 1 libraries.
Loaded plugin rave.ps1.
Loaded plugin reverse.ps1.
Added audio library Sparta_Remix from plugin spartaremix.ps1.
Plugin spartaremix.ps1 added 1 libraries.
Loaded plugin spartaremix.ps1.
Loaded plugin speed.ps1.
Setting Segment_Length to 0.15 for plugin dance.ps1...
Setting No_Music_Chance to 25 for plugin dance.ps1...
Setting Chorus_Enabled to 1 for plugin dsp.ps1...
Setting Vibrato_Enabled to 1 for plugin dsp.ps1...
Setting G_Major_Enabled to 1 for plugin dsp.ps1...
Setting G_Major_Negate to 1 for plugin dsp.ps1...
Generation started.
Seed: 390
Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Single.Parse(String s)
   at YTPPlusPlusPlus.GeneratorFactory.VidThread(Object sender, DoWorkEventArgs e) in D:\Libraries\Documents\YTPPlusPlusPlus\src\ytpplus\GeneratorFactory.cs:line 599
Is a gyan.dev build of FFmpeg installed?
More information was printed to console.txt for troubleshooting.
Generation started.
Seed: 441
Temporary directory deleted.
Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Single.Parse(String s)
   at YTPPlusPlusPlus.GeneratorFactory.VidThread(Object sender, DoWorkEventArgs e) in D:\Libraries\Documents\YTPPlusPlusPlus\src\ytpplus\GeneratorFactory.cs:line 599
Is a gyan.dev build of FFmpeg installed?
More information was printed to console.txt for troubleshooting.

**Comment by KiwifruitDev** [comment]
This software is no longer supported.

https://store.steampowered.com/app/2516360/Nonsensical_Video_Generator/
