### ISSUE TITLE
Can't finish render

### ISSUE THREAD

**Issue by ccateni** [YTP-Plus/YTPPlusPlusPlus#2]
YTP+++ is having trouble rendering...
Its stuck here.
![image](https://user-images.githubusercontent.com/25445255/232621249-11f06ffd-f198-45af-9858-ed1df43f09da.png)

**Comment by HippotamusAmphibious** [comment]
How did you get the program to work? It didn't opened it for me

**Comment by KiwifruitDev** [comment]
Try v3.0.1 to see if this solves the issue.

**Comment by KiwifruitDev** [comment]
Hi, any update? If there are any more problems, be sure to let me know.
If not, I'll close this issue. :)

**Comment by ccateni** [comment]
Ok, updated the software, and now theres a new issue.

The render errors saying "Could not find file [YTPPlusPluslocation]\Temp\TempOutput.mp4.

**Comment by BumpDrafting** [comment]
> 

same

**Comment by BumpDrafting** [comment]
> Contributor

Nope still broken

**Comment by KiwifruitDev** [comment]
There isn't enough information to keep this issue open, so I'll close it for you. Let me know if you encounter any further problems and I'll re-open it.
