### ISSUE TITLE
I'm getting this strange error that says: "Input String was not in a correct format...

### ISSUE THREAD

**Issue by MartindaYosh** [YTP-Plus/YTPPlusPlusPlus#4]
![Huh](https://user-images.githubusercontent.com/131385706/233434150-e1035f47-d339-434f-8d7f-f25dfd8c6934.PNG)

**Comment by KiwifruitDev** [comment]
Hi, thanks for posting an issue!
Try checking console with ~ (tilde) to see if there's more information.
You may also want to post the `console.txt` file here, if desired.

Here's a tip from the [**The Art of Generation**](https://discord.com/channels/641428540486844417/1098661805859029022) guide post on the YTP+ Hub Discord regarding this error:
- The input string was not in a correct format.
  - This error relates to Windows localization settings.
  - Please ensure that the decimal separator is set to a period (.) in Windows settings.
  - It may also help to move the software to a different location, preferably one that does not contain spaces in the path.

Let me know if this information had helped to solve this issue, and I'll close it for you. :)

**Comment by MartindaYosh** [comment]
Hey there! I've tried out the solution... And it worked! Now it's rendering
my test video no problem at all.

**Comment by KiwifruitDev** [comment]
Glad to hear it's working for you!
I'll close this issue for now. :)
