### ISSUE TITLE
ChopItUp - new tool for ytp

### ISSUE THREAD

**Issue by cookerwatcher** [YTP-Plus/YTPPlusPlusPlus#6]
When making YTP, I often like to cut up peoples speech and re-arrange it...

So I made this tool... https://github.com/cookerwatcher/ChopItUp

It runs speech recognition over one or more input videos and makes a dictionary of words, these are then built up into a library.
You can then ask the script for a sentence or a particular word, and it'll generate a video for you :)  

Might be of use ¯\_(ツ)_/¯

**Comment by KiwifruitDev** [comment]
This software is no longer supported.

https://store.steampowered.com/app/2516360/Nonsensical_Video_Generator/
