### ISSUE TITLE
I got bug

### ISSUE THREAD

**Issue by BambiGaming2022** [YTP-Plus/YTPPlusPlusPlus#7]
When rendering short videos and any short videos

I got this error is "Fatal Error While Getting Length Of Video" and idk how to fix it

My videos is normal
I deleted all files and i thought its gonna work but its not working
Its keeps getting this error
Can you fix it?

**Comment by BambiGaming2022** [comment]
Same as YTP++ and YTP+
I cant save rendered video
When i saved rendered video
Its dont showing in any folders

**Comment by BambiGaming2022** [comment]
This is same error

**Comment by KiwifruitDev** [comment]
Is YTP+++ installed in a directory without spaces? Was the deploy script used?
Let me know if these are the culprits of the issue, otherwise I believe it may be a problem with your FFmpeg/FFprobe installation.

**Comment by BambiGaming2022** [comment]
1. Yes
2. No

**Comment by KiwifruitDev** [comment]
Try using v3.1.3 or higher as FFmpeg is bundled now.

**Comment by KiwifruitDev** [comment]
This software is no longer supported.

https://store.steampowered.com/app/2516360/Nonsensical_Video_Generator/
