### ISSUE TITLE
Could not find file.

### ISSUE THREAD

**Issue by BumpDrafting** [YTP-Plus/YTPPlusPlusPlus#8]
**Describe the bug**
Could not find file.when trying to generate any ytps.

It should have given me a render but no, it just gives me Could not find file.with file location of tempoutput.

**Comment by BumpDrafting** [comment]
Can someone fix it please?

**Comment by KiwifruitDev** [comment]
Please provide more information, such as whether or not you have used the deploy script and if YTP+++ is installed in a directory without spaces. It may also be a problem with your FFmpeg/FFprobe installation.

**Comment by danylopez123** [comment]
This is what i got from the console.txt by just generating a single clip with an intro and outro clip: 

Initialization complete.
Checking for dependencies...





Searching for plugins in .\plugins...
Loading bat plugins...
Loaded plugin Alt._Rainbow.bat.
Loaded plugin Boost.bat.
Loaded plugin Dankify.bat.
Loaded plugin Drunk.bat.
Loaded plugin LuigGroup.bat.
Loaded plugin Reverse_Drunk.bat.
Loaded plugin Spin.bat.
Loaded plugin Super_Spin.bat.
Loaded plugin Warping.bat.
Loading js plugins...
Loaded plugin dance.js.
Loaded plugin distort.js.
Loaded plugin highpitch.js.
Loaded plugin randomsound.js.
Loaded plugin randomsoundmute.js.
Loaded plugin rave.js.
Loaded plugin reverse.js.
Loaded plugin speedup.js.
Loaded plugin vibrato.js.
Loading py plugins...
No updates available.
Generation started.
Seed: 571
Temporary directory deleted.
Intro clip enabled, adding 1 to max clips. New max clips is 2.
ffmpeg version N-55702-g920046a Copyright (c) 2000-2013 the FFmpeg developers
  built on Aug 21 2013 18:10:00 with gcc 4.7.3 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      52. 42.100 / 52. 42.100
  libavcodec     55. 29.100 / 55. 29.100
  libavformat    55. 14.101 / 55. 14.101
  libavdevice    55.  3.100 / 55.  3.100
  libavfilter     3. 82.100 /  3. 82.100
  libswscale      2.  5.100 /  2.  5.100
  libswresample   0. 17.103 /  0. 17.103
  libpostproc    52.  3.100 / 52.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\library\video\intros\NeoGeo_Intro.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
  Duration: 00:00:07.87, start: 0.021333, bitrate: 378 kb/s
    Stream #0:0(und): Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s
    Metadata:
      handler_name    : SoundHandler
    Stream #0:1(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 960x720 [SAR 1:1 DAR 4:3], 235 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc
    Metadata:
      handler_name    : VideoHandler
[Parsed_setsar_1 @ 0000000000e24fa0] num:den syntax is deprecated, please use num/den or named options instead
[libx264 @ 0000000000e235e0] using SAR=1/1
[libx264 @ 0000000000e235e0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX AVX2 FMA3 LZCNT BMI2
[libx264 @ 0000000000e235e0] profile High, level 3.0
[libx264 @ 0000000000e235e0] 264 - core 135 r2345 f0c1c53 - H.264/MPEG-4 AVC codec - Copyleft 2003-2013 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '.\temp\video0.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf55.14.101
    Stream #0:0(und): Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv420p, 640x480 [SAR 1:1 DAR 4:3], q=-1--1, 15360 tbn, 30 tbc
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (libvo_aacenc) ([64][0][0][0] / 0x0040), 44100 Hz, mono, s16, 128 kb/s
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:1 -> #0:0 (h264 -> libx264)
  Stream #0:0 -> #0:1 (aac -> libvo_aacenc)
Press [q] to stop, [?] for help
frame=  140 fps=0.0 q=29.0 size=      89kB time=00:00:04.77 bitrate= 152.9kbits/s dup=1 drop=0    
frame=  238 fps=0.0 q=-1.0 Lsize=     195kB time=00:00:07.90 bitrate= 202.2kbits/s dup=1 drop=0    

video:62kB audio:124kB subtitle:0 global headers:0kB muxing overhead 5.065853%
[libx264 @ 0000000000e235e0] frame I:2     Avg QP:16.03  size:   311
[libx264 @ 0000000000e235e0] frame P:90    Avg QP:18.72  size:   587
[libx264 @ 0000000000e235e0] frame B:146   Avg QP:15.52  size:    62
[libx264 @ 0000000000e235e0] consecutive B-frames: 16.8%  3.4%  2.5% 77.3%
[libx264 @ 0000000000e235e0] mb I  I16..4: 54.8% 44.5%  0.7%
[libx264 @ 0000000000e235e0] mb P  I16..4:  2.1%  2.1%  0.5%  P16..4:  4.0%  1.0%  0.5%  0.0%  0.0%    skip:89.8%
[libx264 @ 0000000000e235e0] mb B  I16..4:  0.0%  0.6%  0.0%  B16..8:  1.0%  0.1%  0.0%  direct: 0.1%  skip:98.2%  L0:45.8% L1:45.2% BI: 9.0%
[libx264 @ 0000000000e235e0] 8x8 transform intra:50.7% inter:39.1%
[libx264 @ 0000000000e235e0] coded y,uvDC,uvAC intra: 4.6% 1.9% 1.4% inter: 0.6% 0.3% 0.1%
[libx264 @ 0000000000e235e0] i16 v,h,dc,p: 93%  5%  2%  0%
[libx264 @ 0000000000e235e0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 36% 14% 49%  0%  0%  0%  0%  0%  0%
[libx264 @ 0000000000e235e0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 38% 27% 24%  2%  2%  2%  2%  2%  2%
[libx264 @ 0000000000e235e0] i8c dc,h,v,p: 95%  2%  3%  0%
[libx264 @ 0000000000e235e0] Weighted P-Frames: Y:30.0% UV:3.3%
[libx264 @ 0000000000e235e0] ref P L0: 69.6% 12.5% 11.5%  5.3%  1.1%
[libx264 @ 0000000000e235e0] ref B L0: 74.7% 23.5%  1.8%
[libx264 @ 0000000000e235e0] ref B L1: 98.4%  1.6%
[libx264 @ 0000000000e235e0] kb/s:62.93
.\library\video\materials\iteachvader\Robotnik Forgets to Install Antivirus.mp4
CLIP DURATION: 242,231
STARTING CLIP video1
Beginning of clip 1: 98,63519
Ending of clip 1: 113,591286
ffmpeg version N-55702-g920046a Copyright (c) 2000-2013 the FFmpeg developers
  built on Aug 21 2013 18:10:00 with gcc 4.7.3 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      52. 42.100 / 52. 42.100
  libavcodec     55. 29.100 / 55. 29.100
  libavformat    55. 14.101 / 55. 14.101
  libavdevice    55.  3.100 / 55.  3.100
  libavfilter     3. 82.100 /  3. 82.100
  libswscale      2.  5.100 /  2.  5.100
  libswresample   0. 17.103 /  0. 17.103
  libpostproc    52.  3.100 / 52.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\library\video\materials\iteachvader\Robotnik Forgets to Install Antivirus.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2018-11-13 02:09:02
  Duration: 00:04:02.23, start: 0.000000, bitrate: 1045 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 960x720 [SAR 1:1 DAR 4:3], 913 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc
    Metadata:
      creation_time   : 2018-11-13 02:09:02
      handler_name    : ISO Media file produced by Google Inc. Created on: 11/12/2018.
    Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      creation_time   : 2018-11-13 02:06:29
      handler_name    : ISO Media file produced by Google Inc. Created on: 11/12/2018.
[Parsed_setsar_1 @ 0000000002665980] num:den syntax is deprecated, please use num/den or named options instead
[libx264 @ 0000000002ca00a0] using SAR=1/1
[libx264 @ 0000000002ca00a0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX AVX2 FMA3 LZCNT BMI2
[libx264 @ 0000000002ca00a0] profile High, level 3.0
[libx264 @ 0000000002ca00a0] 264 - core 135 r2345 f0c1c53 - H.264/MPEG-4 AVC codec - Copyleft 2003-2013 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '.\temp\video1.mp4':
  Metadata:
    encoder         : Lavf55.14.101
    Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv420p, 640x480 [SAR 1:1 DAR 4:3], q=-1--1, 15360 tbn, 30 tbc
    Stream #0:1: Audio: aac (libvo_aacenc) ([64][0][0][0] / 0x0040), 44100 Hz, mono, s16, 128 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (h264 -> libx264)
  Stream #0:1 -> #0:1 (aac -> libvo_aacenc)
Press [q] to stop, [?] for help
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A    
frame=    0 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A    
frame=  128 fps= 28 q=29.0 size=     315kB time=00:00:03.51 bitrate= 733.9kbits/s    
frame=  268 fps= 53 q=29.0 size=     783kB time=00:00:08.18 bitrate= 783.7kbits/s    
frame=  370 fps= 67 q=29.0 size=    1241kB time=00:00:11.59 bitrate= 876.7kbits/s    
Outro clip enabled, adding 1 to max clips. New max clips is 3.
STARTING CLIP video3
ffmpeg version N-55702-g920046a Copyright (c) 2000-2013 the FFmpeg developers
  built on Aug 21 2013 18:10:00 with gcc 4.7.3 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      52. 42.100 / 52. 42.100
  libavcodec     55. 29.100 / 55. 29.100
  libavformat    55. 14.101 / 55. 14.101
  libavdevice    55.  3.100 / 55.  3.100
  libavfilter     3. 82.100 /  3. 82.100
  libswscale      2.  5.100 /  2.  5.100
  libswresample   0. 17.103 /  0. 17.103
  libpostproc    52.  3.100 / 52.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\library\video\outros\ytpplus_sfm_outro.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2023-02-09 13:27:48
  Duration: 00:00:07.21, start: 0.000000, bitrate: 5716 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 5524 kb/s, 24 fps, 24 tbr, 24k tbn, 48 tbc
    Metadata:
      creation_time   : 2023-02-09 13:27:51
      handler_name    : Mainconcept MP4 Video Media Handler
    Stream #0:1(eng): Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 188 kb/s
    Metadata:
      creation_time   : 2023-02-09 13:27:51
      handler_name    : Mainconcept MP4 Sound Media Handler
[Parsed_setsar_1 @ 0000000003040ea0] num:den syntax is deprecated, please use num/den or named options instead
[libx264 @ 00000000025e8400] using SAR=1/1
[libx264 @ 00000000025e8400] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX AVX2 FMA3 LZCNT BMI2
[libx264 @ 00000000025e8400] profile High, level 3.0
[libx264 @ 00000000025e8400] 264 - core 135 r2345 f0c1c53 - H.264/MPEG-4 AVC codec - Copyleft 2003-2013 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '.\temp\video3.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf55.14.101
    Stream #0:0(eng): Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv420p, 640x480 [SAR 1:1 DAR 4:3], q=-1--1, 15360 tbn, 30 tbc
    Metadata:
      creation_time   : 2023-02-09 13:27:51
      handler_name    : Mainconcept MP4 Video Media Handler
    Stream #0:1(eng): Audio: aac (libvo_aacenc) ([64][0][0][0] / 0x0040), 44100 Hz, mono, s16, 128 kb/s
    Metadata:
      creation_time   : 2023-02-09 13:27:51
      handler_name    : Mainconcept MP4 Sound Media Handler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 -> libx264)
  Stream #0:1 -> #0:1 (aac -> libvo_aacenc)
Press [q] to stop, [?] for help
frame=  126 fps=0.0 q=29.0 size=     144kB time=00:00:04.14 bitrate= 285.3kbits/s    
frame=  216 fps=0.0 q=-1.0 Lsize=     402kB time=00:00:07.20 bitrate= 456.4kbits/s    

video:280kB audio:113kB subtitle:0 global headers:0kB muxing overhead 2.043292%
[libx264 @ 00000000025e8400] frame I:2     Avg QP:15.65  size:  2392
[libx264 @ 00000000025e8400] frame P:140   Avg QP:21.53  size:  1926
[libx264 @ 00000000025e8400] frame B:74    Avg QP:23.70  size:   161
[libx264 @ 00000000025e8400] consecutive B-frames: 53.7%  0.9%  2.8% 42.6%
[libx264 @ 00000000025e8400] mb I  I16..4: 71.5% 26.5%  2.0%
[libx264 @ 00000000025e8400] mb P  I16..4:  2.5%  3.8%  0.2%  P16..4: 25.2%  2.6%  2.1%  0.0%  0.0%    skip:63.6%
[libx264 @ 00000000025e8400] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8:  4.1%  0.6%  0.2%  direct: 0.1%  skip:94.9%  L0:17.4% L1:70.4% BI:12.1%
[libx264 @ 00000000025e8400] 8x8 transform intra:52.2% inter:76.6%
[libx264 @ 00000000025e8400] coded y,uvDC,uvAC intra: 20.2% 13.0% 1.4% inter: 4.3% 3.8% 0.0%
[libx264 @ 00000000025e8400] i16 v,h,dc,p: 38%  9%  5% 49%
[libx264 @ 00000000025e8400] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 19%  6% 56%  3%  4%  4%  3%  3%  2%
[libx264 @ 00000000025e8400] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 38% 14% 20%  4%  6%  7%  4%  4%  2%
[libx264 @ 00000000025e8400] i8c dc,h,v,p: 84%  7%  9%  1%
[libx264 @ 00000000025e8400] Weighted P-Frames: Y:22.1% UV:17.9%
[libx264 @ 00000000025e8400] ref P L0: 63.0%  5.4% 22.5%  6.9%  2.2%
[libx264 @ 00000000025e8400] ref B L0: 91.3%  7.6%  1.1%
[libx264 @ 00000000025e8400] ref B L1: 83.7% 16.3%
[libx264 @ 00000000025e8400] kb/s:318.20
Concatenating clips...
ffmpeg version N-55702-g920046a Copyright (c) 2000-2013 the FFmpeg developers
  built on Aug 21 2013 18:10:00 with gcc 4.7.3 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      52. 42.100 / 52. 42.100
  libavcodec     55. 29.100 / 55. 29.100
  libavformat    55. 14.101 / 55. 14.101
  libavdevice    55.  3.100 / 55.  3.100
  libavfilter     3. 82.100 /  3. 82.100
  libswscale      2.  5.100 /  2.  5.100
  libswresample   0. 17.103 /  0. 17.103
  libpostproc    52.  3.100 / 52.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\temp\video0.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf55.14.101
  Duration: 00:00:07.93, start: 0.036281, bitrate: 201 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 640x480 [SAR 1:1 DAR 4:3], 63 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 128 kb/s
    Metadata:
      handler_name    : SoundHandler
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000000000fbb660] moov atom not found
.\temp\video1.mp4: Invalid data found when processing input
Concatenation failed.
Trying a different method of concatenation.
ffmpeg version N-55702-g920046a Copyright (c) 2000-2013 the FFmpeg developers
  built on Aug 21 2013 18:10:00 with gcc 4.7.3 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      52. 42.100 / 52. 42.100
  libavcodec     55. 29.100 / 55. 29.100
  libavformat    55. 14.101 / 55. 14.101
  libavdevice    55.  3.100 / 55.  3.100
  libavfilter     3. 82.100 /  3. 82.100
  libswscale      2.  5.100 /  2.  5.100
  libswresample   0. 17.103 /  0. 17.103
  libpostproc    52.  3.100 / 52.  3.100
[concat @ 0000000000e8cc00] Impossible to open 'video0.mp4'
.\temp\concat.txt: No such file or directory
Saving to library...
An error occurred while generating the video.
Could not find file 'D:\YTPPlusPlusPlus\temp\tempoutput.mp4'.

**Comment by KiwifruitDev** [comment]
Try using v3.1.3 as it contains many stability improvements alongside FFmpeg bundled with it.

**Comment by KiwifruitDev** [comment]
This software is no longer supported.

https://store.steampowered.com/app/2516360/Nonsensical_Video_Generator/
